### PR TITLE
Better naming config.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by xepozz** [comment]
I don't like it. 
All files are available to modifing so when I want change yiisoft cache to another implementation I need to create new file and remove old instead of modifing content.

**Comment by terabytesoftw** [comment]
> I don't like it.
> All files are available to modifing so when I want change yiisoft cache to another implementation I need to create new file and remove old instead of modifing content.

Well in that aspect you are right, but at the same time it is more specific, which I think is better, for example if you have several caches, will you put them in the same file from different implementations?

**Comment by xepozz** [comment]
It depends. Often yes than no.
When I want to do with caches I just open cache.php. In other hand I need to iterate *-cache.php files.

Also format *-cache don't groups files in the row.
yiisoft-cache and {vendor}-cache will be placed in different places in a directory list.

**Comment by terabytesoftw** [comment]
Because they will be placed in different directories, if they are in the same configuration directory :)

**Comment by samdark** [comment]
Checked. I like current layout way more. It's more intuitive. A bit less verbose but more intuitive.

**Pull request closed without merging**
