### PR TITLE
Remove resolving container from itself.

### PR DESCRIPTION
**Pull request by Nex-Otaku**
There is no need to resolve container from itself.

| Q             | A
| ------------- | ---
| Is bugfix?    | No
| New feature?  | No
| Breaks BC?    | No
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by xepozz** [comment]
Tests failed

**Comment by roxblnfk** [comment]
> Tests failed

In the current `master` branch tests also failed

**Comment by terabytesoftw** [comment]
@Nex-Otaku please update master in branch.

**Comment by Nex-Otaku** [comment]
> @Nex-Otaku please update branch with master.

Done

**Comment by terabytesoftw** [comment]
:+1:

**Pull request merged**
