### PR TITLE
make `composer run serve` work on windows

### PR DESCRIPTION
**Pull request by anovsiradj**
serve add `@php` because windows dont understand shebang on `./yii`

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Would be good to do a fix at https://github.com/yiisoft/app-api/blob/master/composer.json#L91 and in demo.

**Comment by terabytesoftw** [comment]
image

Exactly what the problem is, it works perfectly in the Windows 11 console.

**Comment by samdark** [comment]
https://github.com/yiisoft/app/pull/311#pullrequestreview-1873159388

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
