### PR TITLE
Remove debug inspection API from localization

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by vjik — COMMENTED** [review]
@xepozz May be you whole remove localization from application template?

**Review by samdark — APPROVED** [review]

**Comment by xepozz** [comment]
@vjik `¯\_(ツ)_/¯ `

**Comment by samdark** [comment]
Any idea what's wrong with tests?

**Comment by xepozz** [comment]
I think they're all failed because of:
```
There was 1 error:
1) SiteControllerTest: Get index
 Test  tests/Functional/SiteControllerTest.php:testGetIndex

  [ParseError] syntax error, unexpected token "readonly", expecting "abstract" or "final" or "class"  

#1  /home/runner/work/app/app/vendor/yiisoft/yii-debug-api/src/Debug/Http/HttpApplicationWrapper.php:12
```

**Comment by vjik** [comment]
@xepozz is right. Yii Debug API declared that support PHP 8.1, but use PHP 8.2 feature "readonly".

**Pull request merged**
